In [3]:
# sets to be used
Ω = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12} # universal set
A = {2, 4, 6, 8, 10} 
B = {3, 8, 11, 12}
C = {2, 3, 6, 8, 9, 11}

In [ ]:
# $ A \cap B$
# we are looking for the intersection of sets A and B i.e set of all elements common in both A and B
intersection = A.intersection(B) # using the intersection method to find intersection
print("Intersection of A and B:", intersection)

intersection = A & B # using the '&' operator to find intersection
print("Intersection of A and B using '&':", intersection)

Intersection of A and B: {8}
Intersection of A and B using '&': {8}

In [32]:
# $ A \cup C$
# we are looking for the unions of sets A and C i.e set of all elements in either A, C or both
union = A | C # using the '|' operator to find union
print("Union of A and C using '|':", union)

union = A.union(C) # using the union method to find union
print("Union of A and C using 'union':", union)

Union of A and C using '|': {2, 3, 4, 6, 8, 9, 10, 11}
Union of A and C using 'union': {2, 3, 4, 6, 8, 9, 10, 11}

In [33]:
# A^C
# we are looking for the complement of set A with respect to the universal set Ω
# these are the set of elements not in A but in Ω
A_complement = Ω - A
print("Complement of A with respect to Ω:", A_complement)

Complement of A with respect to Ω: {1, 3, 5, 7, 9, 11, 12}

In [ ]:
# B^C
# we are looking for the complement of set B with respect to the universal set Ω
# these are the set of elements not in B but in Ω   
B_complement = Ω - B 
print("Complement of B with respect to Ω:", B_complement)

Complement of B with respect to Ω: {1, 2, 4, 5, 6, 7, 9, 10}

In [35]:
# complement of the union of A and B
#here we find all the elements in Ω that are not in the union of A and B
A_union_B = A | B # union of A and B
print("Union of A and B:", A_union_B)
A_union_B_complement = Ω - A_union_B
print("Complement of the union of A and B with respect to Ω:", A_union_B_complement)

Union of A and B: {2, 3, 4, 6, 8, 10, 11, 12}
Complement of the union of A and B with respect to Ω: {1, 5, 9, 7}

In [9]:
#find all elements that are in B and not in C or the intersection of B and complement of C
C_complement = Ω - C
print("Complement of C with respect to Ω:", C_complement)
result = B & C_complement
print("Elements in B and not in C:", result)

Complement of C with respect to Ω: {1, 4, 5, 7, 10, 12}
Elements in B and not in C: {12}

In [36]:
# A\B
#find all elements that are in A but not in B(relative compliment)
A_minus_B = A - B
print("Elements in A but not in B:", A_minus_B)

A_minus_B = A.difference(B)  # using the difference method to find relative complement
print("Elements in A but not in B using 'difference':", A_minus_B)

Elements in A but not in B: {2, 10, 4, 6}
Elements in A but not in B using 'difference': {2, 10, 4, 6}

In [27]:
#C\(B\A)
# find elements that are in C that are not in the result of B\A
B_minus_A = B - A
print("Elements in B but not in A:", B_minus_A)
C_minus_B_minus_A = C - B_minus_A
print("Elements in C but not in (B - A):", C_minus_B_minus_A)

Elements in B but not in A: {11, 3, 12}
Elements in C but not in (B - A): {8, 9, 2, 6}

In [ ]:
# (C∩A)∪(C∖B)
# find all elements that are either in both C and A or in C but not in B
C_intersection_A = C & A # using the '&' operator to find intersection
C_minus_B = C - B # using the '-' operator to find relative complement
C_union = C_intersection_A | C_minus_B # using the '|' operator to find union
print("Elements in (C ∩ A) ∪ (C ∖ B):", C_union)

Elements in (C ∩ A) ∪ (C ∖ B): {2, 6, 8, 9}

#### verify answers

In [ ]:
#verify the intersection of sets A and B
intersection = A.intersection(B) 
print(intersection == {8}) # True if the intersection is correct

True

In [ ]:
# verify the unions of set A and C
union = A.union(C)
print(union == {2, 3, 4, 6, 8, 9, 10, 11}) # True if the union is correct

True

In [18]:
#verify A^C
A_complement = Ω - A
print(A_complement == {1, 3, 5, 7, 9, 11, 12}) # True if the complement is correct

True

In [ ]:
# verify B^C
B_complement = Ω - B
print(B_complement == {1, 2, 4, 5, 6, 7, 9, 10}) # True if the complement is correct

True

In [22]:
# verify complement of the union of A and B
A_union_B = A | B 
A_union_B_complement = Ω - A_union_B
print(A_union_B_complement == {1, 5, 7, 9}) # True if the complement is correct

True

In [23]:
#verify BnC'
C_complement = Ω - C
result = B & C_complement
print(result == {12})

True

In [26]:
# verify A\B
A_minus_B = A - B
print(A_minus_B == {2, 4, 6, 10}) # True

True

In [29]:
#verify C\(B\A)
B_minus_A = B - A
C_minus_B_minus_A = C - B_minus_A
print(C_minus_B_minus_A == {8, 9, 2, 6}) # True if the result is correct

True

In [33]:
#verify (C∩A)∪(C∖B)
C_intersection_A = C & A
C_minus_B = C - B
C_union = C_intersection_A | C_minus_B
print(C_union == {2, 6, 8, 9}) # True if the union is correct
print("All set operations verified successfully.")

True
All set operations verified successfully.

In [ ]:
# inclusion exclusion principle
# In set theory, the Inclusion-Exclusion Principle helps us accurately count the number of elements in unions
# of sets — avoiding double-counting of overlapping elements

# calculate right_hand_equation
# |A∪B∪C| = |A| + |B| + |C| - |A∩B| - |A∩C| - |B∩C| + |A∩B∩C|
A = {2, 4, 6, 8, 10}
B = {3, 8, 11, 12}
C = {2, 3, 6, 8, 9, 11}

# sizes of individual sets
size_A = print(len(A))
size_B = print(len(B))
size_C = print(len(C))

5
4
6

In [14]:
# pairwise intersections
intersection_AB = print(A.intersection(B))
intersection_AC = print(A.intersection(C)) 
intersection_BC = print(B.intersection(C))

len(A.intersection(B))

{8}
{8, 2, 6}
{8, 11, 3}

1

In [12]:
len(A.intersection(C))

3

In [13]:
len(B.intersection(C))

3

In [15]:
# intersection of all 3
intersection_ABC = A.intersection(B).intersection(C)
print("Intersection of A, B, and C:", intersection_ABC)

len(A.intersection(B).intersection(C))

Intersection of A, B, and C: {8}

1

In [24]:
# applying the inclusion-exclusion formula
# |A∪B∪C| = |A| + |B| + |C| - |A∩B| - |A∩C| - |B∩C| + |A∩B∩C|
right_hand_equation = len(A) + len(B) + len(C) - len(A.intersection(B)) - len(A.intersection(C)) - len(B.intersection(C)) + len(A.intersection(B).intersection(C))
print("right_hand_equation:", right_hand_equation)

right_hand_equation: 9

In [23]:
# calculate left_hand_equation
left_hand_equation = A | B | C
len(A.union(B.union(C)))  # This should equal the result from the inclusion-exclusion formula
print("left_hand_equation:", len(A.union(B.union(C))))  # This should equal the result from the inclusion-exclusion formula

left_hand_equation: 9

In [39]:
# using a comparison operator
len(A | B |C) ==  len(A) + len(B) + len(C) - len(A.intersection(B)) - len(A.intersection(C)) - len(B.intersection(C)) + len(A.intersection(B).intersection(C))
# returns true thus right_hand_equation == left_hand_equation

True

In [40]:
print("Inclusion-Exclusion Principle holds true:", len(A | B | C) == right_hand_equation)

Inclusion-Exclusion Principle holds true: True

In [49]:
# set operations in python
Nina = set(["Cat","Dog","Rabbit","Donkey","Parrot", "Goldfish"])
Mary = set(["Dog","Chinchilla","Horse", "Chicken"])
Eve = set(["Rabbit", "Turtle", "Goldfish"])

In [45]:
# Eve's turtle passed away, to update her list
Eve = set(["Rabbit", "Turtle", "Goldfish"])
# remove the turtle
Eve.remove("Turtle")
print("Updated Eve's list:", Eve)

Updated Eve's list: {'Rabbit', 'Goldfish'}

In [41]:
# Nina and Mary have a pet in common
Nina = set(["Cat","Dog","Rabbit","Donkey","Parrot", "Goldfish"])
Mary = set(["Dog","Chinchilla","Horse", "Chicken"])

# combine both sets using union
nina_updated = Nina.union(Mary)
print("Nina's updated pet list:", nina_updated)

Nina's updated pet list: {'Donkey', 'Parrot', 'Chicken', 'Rabbit', 'Cat', 'Dog', 'Horse', 'Chinchilla', 'Goldfish'}

In [42]:
# mary to clear her list while away
Mary = set(["Dog","Chinchilla","Horse", "Chicken"])

# clear the set
Mary.clear()
print("Mary's pet list after clearing:", Mary) # Mary should be an empty set now

Mary's pet list after clearing: set()

In [43]:
# number of species Nina is currently taking care of
nina_species_count = len(nina_updated)
print("Number of species Nina is currently taking care of:", nina_species_count)

Number of species Nina is currently taking care of: 9

In [46]:
# Nina asks eve to take care of common species,update nina's collection
common_species = nina_updated.intersection(Eve)

# remove common species from Nina's collection
nina_updated = nina_updated - common_species

print("Common species given to Eve:", common_species)
print("Nina's updated collection:", nina_updated)

Common species given to Eve: {'Rabbit', 'Goldfish'}
Nina's updated collection: {'Donkey', 'Parrot', 'Chicken', 'Cat', 'Dog', 'Horse', 'Chinchilla'}

In [ ]:
import pandas as pd

# Load Europe and EU
europe = pd.read_excel('Europe_and_EU.xlsx', sheet_name = 'Europe') 
eu = pd.read_excel('Europe_and_EU.xlsx', sheet_name = 'EU')

In [49]:
print(europe.columns)
print(eu.columns)

Index(['Rank', 'Country', 'Population', '% of population',
       'Average relative annual growth (%)', 'Average absolute annual growth',
       'Estimated doubling time (Years)', 'Official figure (where available)',
       'Date of last figure', 'Regional grouping', 'Source'],
      dtype='object')
Index(['Rank', 'Country', '2017 population', '% of pop.',
       'Average relative annual growth', 'Average absolute annual growth',
       'Official figure', 'Date of last figure', 'Source'],
      dtype='object')

In [50]:
# Remove leading/trailing whitespace from country names
europe['Country'] = europe['Country'].str.strip()
eu['Country'] = eu['Country'].str.strip()

In [51]:
# preview the data
europe.head(3)

,Rank,Country,Population,% of population,Average relative annual growth (%),Average absolute annual growth,Estimated doubling time (Years),Official figure (where available),Date of last figure,Regional grouping,Source
0,1.0,Russia,143964709,17.15,0.19,294285,368,146839993,2017-01-01 00:00:00,EAEU,[1]
1,2.0,Germany,82521653,9.80,1.20,600000,90,82800000,2016-12-31 00:00:00,EU,Official estimate
2,3.0,Turkey,80810000,9.60,1.34,1035000,52,77695904,2016-12-31 00:00:00,NaN,[2]

In [52]:
eu.head(3)

,Rank,Country,2017 population,% of pop.,Average relative annual growth,Average absolute annual growth,Official figure,Date of last figure,Source
0,1,Germany,82800000,16.18,0.76,628876,82576900,2017-03-31,Official estimate
1,2,France,67210459,13.10,0.40,265557,67174000,2018-01-01,Monthly official estimate
2,3,United Kingdom,65808573,12.86,0.65,428793,65648100,2017-06-30,Official estimate

In [53]:
# Convert both columns to sets
europe_set = set(europe['Country'])
eu_set = set(eu['Country'])

# Check if EU is a subset of Europe
is_subset = eu_set.issubset(europe_set)

print("Is EU a subset of Europe?", is_subset)

Is EU a subset of Europe? True

In [ ]:
# Set difference: countries in Europe but not in the EU
non_eu_europe = europe_set - eu_set

print("Countries in Europe but not in the EU:")
print(non_eu_europe)

# europe_set - eu_set returns all countries that are in europe_set but not in eu_set.

Countries in Europe but not in the EU:
{'Guernsey (UK)', 'Gibraltar (UK)', 'Liechtenstein', 'Belarus', 'Moldova', 'Andorra', 'Åland Islands (Finland)', 'Russia', 'Montenegro', 'Kosovo', 'San Marino', 'Albania', 'Norway', 'Armenia', 'Bosnia and Herzegovina', 'Iceland', 'Switzerland', 'Serbia', 'Faroe Islands (Denmark)', 'Azerbaijan', 'Vatican City', 'Monaco', 'Macedonia', 'Ukraine', 'Georgia', 'Jersey (UK)', 'Svalbard (Norway)', 'Isle of Man (UK)', 'Turkey'}